apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-24T17:55:06Z"
  labels:
    app: nginx-web
  name: nginx-service
  namespace: default
  resourceVersion: "19609"
  uid: 216ebec5-6d78-4347-9818-dff42e64ca2e
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.107.138.52
  clusterIPs:
  - 10.107.138.52
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32535
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-web
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
