apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-web
  namespace: default
  uid: 82cccd4b-b676-427e-9edd-2e38bab98ed0
  resourceVersion: '460639'
  creationTimestamp: '2024-05-30T01:34:47Z'
  managedFields:
    - manager: kubectl-autoscale
      operation: Update
      apiVersion: autoscaling/v1
      time: '2024-05-30T01:34:47Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:maxReplicas: {}
          f:minReplicas: {}
          f:scaleTargetRef: {}
          f:targetCPUUtilizationPercentage: {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: autoscaling/v2
      time: '2024-05-30T01:40:04Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:conditions:
            .: {}
            k:{"type":"AbleToScale"}:
              .: {}
              f:lastTransitionTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"ScalingActive"}:
              .: {}
              f:lastTransitionTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"ScalingLimited"}:
              .: {}
              f:lastTransitionTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:currentMetrics: {}
          f:currentReplicas: {}
          f:desiredReplicas: {}
      subresource: status
  selfLink: /apis/autoscaling/v2/namespaces/default/horizontalpodautoscalers/nginx-web
status:
  currentReplicas: 4
  desiredReplicas: 4
  currentMetrics:
    - type: Resource
      resource:
        name: cpu
        current:
          averageValue: '0'
          averageUtilization: 0
  conditions:
    - type: AbleToScale
      status: 'True'
      lastTransitionTime: '2024-05-30T01:35:02Z'
      reason: ReadyForNewScale
      message: recommended size matches current size
    - type: ScalingActive
      status: 'True'
      lastTransitionTime: '2024-05-30T01:35:02Z'
      reason: ValidMetricFound
      message: >-
        the HPA was able to successfully calculate a replica count from cpu
        resource utilization (percentage of request)
    - type: ScalingLimited
      status: 'True'
      lastTransitionTime: '2024-05-30T01:40:04Z'
      reason: TooFewReplicas
      message: the desired replica count is less than the minimum replica count
spec:
  scaleTargetRef:
    kind: Deployment
    name: nginx-web
    apiVersion: apps/v1
  minReplicas: 4
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
