apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
    deployment.kubernetes.io/revision: "38"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"10"},"creationTimestamp":"2024-05-24T14:43:06Z","generation":11,"labels":{"app":"nginx-web"},"name":"nginx-web","namespace":"default","resourceVersion":"18230","uid":"5e5f5ac2-c782-4694-aea4-f0998718be37"},"spec":{"progressDeadlineSeconds":600,"replicas":4,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"nginx-web"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"date":"1716567141","kubectl.kubernetes.io/restartedAt":"2024-05-24T13:27:00-04:00"},"creationTimestamp":null,"labels":{"app":"nginx-web"}},"spec":{"containers":[{"env":[{"name":"DEPLOY_DATE","value":"Fri May 24 01:22:17 PM EDT 2024"}],"image":"technotuba/nginx:initial","imagePullPolicy":"Always","name":"nginx","resources":{"requests":{"cpu":"100m"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/usr/share/nginx/html","name":"www-volume"},{"mountPath":"/etc/nginx/nginx.conf","name":"config-volume","subPath":"nginx.conf"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"configMap":{"defaultMode":420,"name":"www-configmap"},"name":"www-volume"},{"configMap":{"defaultMode":420,"name":"nginx-config"},"name":"config-volume"}]}}},"status":{"availableReplicas":4,"conditions":[{"lastTransitionTime":"2024-05-24T14:43:40Z","lastUpdateTime":"2024-05-24T14:43:40Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2024-05-24T17:17:49Z","lastUpdateTime":"2024-05-24T17:39:53Z","message":"ReplicaSet \"nginx-web-78886f8c96\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":11,"readyReplicas":4,"replicas":4,"updatedReplicas":4}}
  creationTimestamp: "2024-05-24T14:43:06Z"
  generation: 40
  labels:
    app: nginx-web
  name: nginx-web
  namespace: default
  resourceVersion: "246979"
  uid: 5e5f5ac2-c782-4694-aea4-f0998718be37
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        date: "1716567141"
        kubectl.kubernetes.io/restartedAt: "2024-05-28T06:29:59-04:00"
      creationTimestamp: null
      labels:
        app: nginx-web
    spec:
      containers:
      - env:
        - name: DEPLOY_DATE
          value: Fri May 24 01:22:17 PM EDT 2024
        image: technotuba/nginx:v1
        imagePullPolicy: Always
        name: nginx
        resources:
          requests:
            cpu: "100m"  # This line sets the CPU request to 100 milliCPU
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: www-volume
        - mountPath: /etc/nginx/nginx.conf
          name: config-volume
          subPath: nginx.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: www-configmap
        name: www-volume
      - configMap:
          defaultMode: 420
          name: nginx-config
        name: config-volume
status:
  availableReplicas: 4
  conditions:
  - lastTransitionTime: "2024-05-27T11:26:21Z"
    lastUpdateTime: "2024-05-27T11:26:21Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-05-27T11:26:20Z"
    lastUpdateTime: "2024-05-28T10:30:03Z"
    message: ReplicaSet "nginx-web-689f7d664b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 40
  readyReplicas: 4
  replicas: 4
  updatedReplicas: 4
